@startuml
autonumber
actor "Customer" as MEDLT

activate MEDLT
MEDLT-> ":System" : Answer  Survey

activate ":System"
":System" --> MEDLT : Show list of Survey to answer

deactivate ":System"


MEDLT-> ":System" : selects survey to be answered
activate ":System"

loop while has questions
":System" ->  MEDLT: show question
deactivate ":System"

MEDLT-> ":System" : answer to question

end loop
activate ":System"
deactivate ":System"
@enduml